import Head from "next/head";
import Hompeage from "../components/Hompeage";
import styles from "../styles/Home.module.css";
import { getSession } from "next-auth/react";
import { getAuth } from "firebase-auth";

export default function Home(session) {
  // if (Object.keys(session) === 0) console.log("no session");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Hompeage />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
}
